# Generated by Django 4.0.3 on 2022-03-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
