# Generated by Django 4.0.3 on 2022-03-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
